import { StyleSheet } from "@react-pdf/renderer";
import { PDF_BRAND } from "./brand";

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 98,
    paddingBottom: 40,
    paddingHorizontal: 36,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: PDF_BRAND.text,
  },
  header: {
    position: "absolute",
    top: 0,
    left: 36,
    right: 36,
    height: 92,
    paddingTop: 22,
    paddingBottom: 14,
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 2,
    borderBottomColor: PDF_BRAND.primary,
  },
  logoBox: {
    width: 52,
    height: 52,
    marginRight: 12,
    borderWidth: 1,
    borderColor: PDF_BRAND.border,
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  logo: { width: "100%", height: "100%", objectFit: "contain" },
  businessName: { fontSize: 18, fontFamily: "Helvetica-Bold", color: PDF_BRAND.primary },
  businessDetail: { fontSize: 8.5, color: PDF_BRAND.textDim, marginTop: 4 },
  docTitle: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    color: PDF_BRAND.primary,
    textAlign: "right",
    letterSpacing: 0.3,
  },
  docDate: { fontSize: 8.5, color: PDF_BRAND.textDim, textAlign: "right", marginTop: 4 },
  footer: {
    position: "absolute",
    bottom: 16,
    left: 36,
    right: 36,
    fontSize: 7.5,
    color: PDF_BRAND.textDim,
    textAlign: "center",
  },
});